# Generated by Django 5.2.1 on 2025-06-02 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_passwordentry_domain_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordentry',
            name='domain_extension',
        ),
    ]
