# Generated by Django 5.2.1 on 2025-06-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_passwordentry_domain_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='domain_extension',
            field=models.CharField(default='.com', max_length=10),
        ),
    ]
