# Generated by Django 5.2.1 on 2025-06-02 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_passwordreset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
